# Generated by Django 5.0.2 on 2024-02-29 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 28, 6, 25, 0, 571037, tzinfo=datetime.timezone.utc)),
        ),
    ]
