# Generated by Django 5.0 on 2024-02-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='brand',
            field=models.CharField(db_index=True, default='Gucci', max_length=100, verbose_name='brand'),
            preserve_default=False,
        ),
    ]
